baseURL: https://www.emprendedoresquito.com/

languageCode: es
title: ""
theme: "toha"

summaryLength: 15

# Allow raw html in markdown file
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# Enable Google Analytics
googleAnalytics: UA-122321624-2

# Enable Disqus forum
# disqusShortname: toha-example-site

# Enable global emoji support
enableEmoji: true

# Site parameters
params:
  # Copyright Notice
  copyright: © 2020 Copyright.

  # Meta description for your site.  This will help the search engines to find your site.
  description: Directorio de emprendimientos en Quito.

  # Background image of the landing page
  background: "images/background.jpg"

  # Provide logos for your site. The inverted logo will be used in the initial
  # transparent navbar and the main logo will be used in the non-transparent navbar.
  # It will default to the theme logos if not provided.
  logo:
    main: "/images/main-logo.svg"
    inverted: "/images/inverted-logo.svg"

  # GitHub repo URL of your site
  gitRepo: https://github.com/hossainemruz/toha-example-site

  # specify whether you want to write some blog posts or not
  enableBlogPost: true

  # specify whether you want to show Table of Contents in reading page
  enableTOC: false

  # specify the list of custom menus that you want to show in the top navbar.
  # they will be separated by a divider from the main menus.
  #customMenus:
  #- name: Notes
  #  url: https://hossainemruz.gitbook.io/notes/

  # Provide newsletter configuration. This feature hasn't been implemented yet.
  # Currently, you can just hide it from the footer.
  newsletter:
    enable: true

  # some information about you
  author:
    name: "EMPRENDEDORES"
    nickname: ""
    image: "images/avatar.png"
    # greeting message before your name. it will default to "Hi! I am" if not provided
    greeting: "DIRECTORIO DE"
    # give your contact information. they will be used in the footer
    contactInfo:
      email: "circulodeemprendedoresdequito@gmail.com"
      teléfono: "0986087688"
    # a summary of what you do
    summary:
    - Amamos nuestro trabajo
    - Lo hacemos con excelencia
    - Ayudamos a la economía local